### ISSUE TITLE
config.json needed?

### ISSUE THREAD

**Issue by hemanth** [sindresorhus/hi#1]
First of all uber kool layout :)  [I shall be using it soon ;)]

Using a config file with date like [this](https://registry.npmjs.org/-/user/org.couchdb.user:sindresorhus) and then parsing+populating the index.html would make this more configurable?

**Comment by sindresorhus** [comment]
Nah, it's easy enough to edit the HTML. People will always want to do more than what's available in a config file.

**Comment by hemanth** [comment]
:+1:
