### ISSUE TITLE
Broken layout on Nexus 4

### ISSUE THREAD

**Issue by vinimdocarmo** [sindresorhus/hi#6]
![screenshot_2014-05-03-13-31-35](https://cloud.githubusercontent.com/assets/4542024/2870792/c201a80a-d2e0-11e3-8478-794f350ae222.png)

**Comment by sindresorhus** [comment]
Is this with Chrome or the built-in browser?

**Comment by vinimdocarmo** [comment]
This is with Chrome.

**Comment by vinimdocarmo** [comment]
Now it seems a little different with another color instead of white, but still broken.

![screenshot_2014-05-03-16-27-31](https://cloud.githubusercontent.com/assets/4542024/2871192/044b45ae-d2fa-11e3-8a30-fa277c0486e3.png)
